package aplication.escenarios.controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.image.ImageView;

public class cuentoController {
	@FXML
	private ImageView fondo;
	@FXML
	private Label lblCuento;
	@FXML
	private Label lblTituloCuento;

	
	@SuppressWarnings("unused")
	private void init() {
		lblTituloCuento.setText("Este es el titulo del cuento");
    }
	
	
	// Event Listener on Button.onAction
	@FXML
	public void clic_IniciarJuego(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void clic_Salir(ActionEvent event) {
		// TODO Autogenerated
	}
}
