package aplication.escenarios.controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.layout.Pane;

public class unoController {
	@FXML
	private Pane PUno;
	@FXML
	private Pane PDos;
	@FXML
	private Label titulo;

	// Event Listener on Button.onAction
	@FXML
	public void uno(ActionEvent event) {
		// TODO Autogenerated
		PUno.setVisible(true);
		PDos.setVisible(false);
	}

	// Event Listener on Button.onAction
	@FXML
	public void dos(ActionEvent event) {
		// TODO Autogenerated
		PDos.setVisible(true);
		PUno.setVisible(false);
	}

	public void escenarioUno() {

	}
	
}
